### ISSUE TITLE
Statistics tab in profile.php displays always "0.00 posts per day"

### ISSUE THREAD

**Issue by senky** [phpBB-Social-Network/phpBB-Social-Network#123]
Even when you write at least one post, it will display "0.00 posts per day" in statistics tab in profile.php. Template variable is missing.

http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4413

**Comment by Culprit-CZ** [comment]
WHAT? It is working correctly

**Comment by senky** [comment]
http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4413&p=19006#p19006
