### ISSUE TITLE
Use PHPDoctor/phpDocumentor to generate documentation.

### ISSUE THREAD

**Issue by senky** [phpBB-Social-Network/phpBB-Social-Network#43]
Documentation should be part of every bigger project. SN lacks that, and as it will continue to grow, still more and more developers would like to use its API, what is not documented in no way.

This should contain:
1. adding documentation comments to every function, method and class of SN
2. use [PHPDoctor](https://github.com/peej/phpdoctor/) or [PHPDocumentor](http://www.phpdoc.org/) to generate documentation

Comments are more than welcomed, mainly about if you agree with software used (PHPDoctor), or you know about any other, better software.

This extends #26.

**Comment by Culprit-CZ** [comment]
Can we close it?
We have [phpDoc](http://www.phpdoc.org/) installed on our server and each [github](https://github.com/phpBB-Social-Network/phpBB-Social-Network/tree/develop) update [DEV Site](http://dev.phpbb3hacks.com/socialnetwork/) is [documentation](http://dev.phpbb3hacks.com/sn_culprit/docs/) generated.
We should only put our documentation on some better place.

**Comment by senky** [comment]
No. This issue will be closed after ALL files are checked and properly documented.
