### ISSUE TITLE
Single button click to share status to someone's profile does not work

### ISSUE THREAD

**Issue by senky** [phpBB-Social-Network/phpBB-Social-Network#44]
You need to click twice on Share submit button to send status in profile.php

http://phpbbsocialnetwork.com/viewtopic.php?f=62&t=4156

**Comment by Culprit-CZ** [comment]
#### `EN`

I think it belongs to this issue:
https://github.com/phpBB-Social-Network/phpBB-Social-Network/pull/60

I think that is reported and created twice:
https://github.com/phpBB-Social-Network/phpBB-Social-Network/pull/50

**I think that solution is same for both issues.**

## 

#### `CZ`

Myslím, že to souvisí s tímto issue:
https://github.com/phpBB-Social-Network/phpBB-Social-Network/pull/60

Myslím, že issue bylo vytvořeno dvakrát:
https://github.com/phpBB-Social-Network/phpBB-Social-Network/pull/50

**Myslím, že řešení je společné.**

**Comment by senky** [comment]
This is duplicate of #60.
