### ISSUE TITLE
Hide chat for mobile browsers

### ISSUE THREAD

**Issue by senky** [phpBB-Social-Network/phpBB-Social-Network#45]
Chat in mobile browsers is completelly useless, as it covers nearly half of the screen and does not show at least one chatbox.

It should be hidden and JS responsible for IM should be disabled for mobile browsers so that it does not corrupt final code with big and dead code.

http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=3935

**Comment by Culprit-CZ** [comment]
#### `EN`

I think that is not necessary to create some huge patch. This should be enough.
This will disable IM for mobile devices that have resolution lower than 700px and for all others browsers will be disabled when browser width will be lower than 650px

## 

#### `CZ`

Myslím, že není nutné vytvořit nějaký velký patch. Mohlo by stačit toto:
IM bude vypnuto pokud rozlišení v jednom rozměru mobilního zařízení je nižší než 700px a u všech ostatních prohlížečů bude vypnuto pokud šířka bude menší než 650px

``` js
if ( $.browser.mobile && Math.min($(window).height(),$(window).width()) < 700
    || $(window).width() < 650) {
        $.sn.enableModules.im = false;
}
```

**Comment by senky** [comment]
Resolved in #72 (grr).
