### ISSUE TITLE
Messages on IM are grouped automatically in one

### ISSUE THREAD

**Issue by Kamahl19** [phpBB-Social-Network/phpBB-Social-Network#65]
http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4152

**Comment by Culprit-CZ** [comment]
Who will make it? I have no IDEA how to solve it.

**Comment by balboag** [comment]
It is related with more than 1 tab opened, but I dont know more, sorry.

**Comment by senky** [comment]
Milestone removed, see: http://phpbbsocialnetwork.com/viewtopic.php?p=17858#p17858

**Comment by senky** [comment]
Duplicate of #141.
