### ISSUE TITLE
Resize textarea only for status

### ISSUE THREAD

**Issue by Kamahl19** [phpBB-Social-Network/phpBB-Social-Network#68]
Comment textarea should not be resized when you click on it

**Comment by senky** [comment]
This was not properly discussed, link to topic is missing. I do not like you create issues before we all agree on it...

**Comment by Kamahl19** [comment]
I would say this is a bug because before 0.7.0 we agreed on resizing status textarea when focused, however culprit made it for comments too, but noone like it on comments

**Comment by senky** [comment]
So why it is marked as improvement, if it is bug?

**Comment by balboag** [comment]
+1 to this

**Comment by senky** [comment]
This is duplicate of #142. I will close this one, as #142 is comment-free and contains link to site.
